run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  revive:
    rules:
      - name: exported
        arguments: [false]

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - unparam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
