run:
  timeout: 5m
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  errcheck:
    check-type-assertions: true
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: blank-imports
        disabled: true
      - name: unused-parameter
        disabled: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - unparam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
